### ISSUE TITLE
Checklist for next public stable build

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#117]
**Theme of next build**: First priority: feature parity with [16.11.26](https://github.com/CompletelyFairGames/dwarfcorp/releases) build, but faster and more stable. Second priority: UX enhancements making the game easier to play. Third priority: new game content.

**Requirements for feature parity: fix these regressions since 16.11.26**
Cross-platform requirements:
- [x] Build and test in FNA
- [x] REQUIRED: Fix #85 
- [x] Package FNA builds for OSX / Linux.
- [x] Test on OSX/Linux

GUI requirements:
- [x] Diplomacy/trade screen finished
- [x] Rewrite all tool tips that were erased
- [x] Add key customization back.
- [x] Make resource display work when there are a lot of resources in stocks
- [x] Add number key hotkeys back
- [x] Fix #126

Performance/robustness:
- [x] Test saving/loading. Try to catch corner cases and make sure its robust before releasing the build.
- [ ] Finish up optimization of water
- [ ] Finish optimizing `VoxelListPrimitive`
- [x] Try optimizing the way mining designations are drawn.
- [ ] Measure average performance of 16.11.26 and show that the current version is faster for a sanity check. Make a fancy plot to show how much faster it is!
- [x] Fix #111 
- [x] Required, top priority: fix #128 

**UX enhancements**
- [x] Implement magic/farming in the new menu
- [x] Fix #109 and #110

**New game content**
- [x] Get all new sounds for voxel destruction and mining into the game
- [x] Replace as many dwarf sounds as possible
- [x] Get some of the first new music tracks into the game
- [x] Dwarf animations for climbing.

**Requirements for building a release**
- [x] Generate/package all new builds
- [x] Push to steam
- [x] Write update for website

**Comment by mklingen** [comment]
The build is out, but I will keep this around to remind us to fix some of the outstanding issues.

**Comment by DanoThom** [comment]
Hi, couldn't find a relevant contact link on the project sites - but if you guys are still hiring I'd like to apply. If so, could you provide any publicly available contact details?

**Comment by mklingen** [comment]
Closing and migrating to the July 2017 build.
