### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#209]
The first public for-sale release will be on September 23rd, 2017. Here's what needs to get done.

**Game Features that Must be Tested/Frozen**
- [x] Selecting and moving dwarves.
- [x] Mining blocks. + cancel
- [x] Gathering items
- [x] Building zones + cancel. 
- [x] Remove all rooms except balloon port, stockpile, treasury, cemetery, and animal pen.
- [x] Update tutorial text to reflect change of rooms.
- [x] Building walls + cancel
- [x] Building floors + cancel
- [x] Build objects + cancel
- [x] Make sure doors work/swing the right way.
- [x] Make sure doors block progress of enemy creatures.
- [x] Make sure bear trap works
- [x] Make sure turret works.
- [x] Make sure ladders work
- [x] Building crafts
- [x] Encrusting crafts
- [x] Cancelling tasks
- [x] Direct dwarf control
- [x] Dwarf camera following
- [x] Camera controls and terrain intersection
- [x] Hiring new dwarves
- [x] Firing dwarves
- [x] Farming / auto-farming
- [x] Cooking
- [x] Guarding. Make sure this can be cancelled, and dwarves respond to threats
- [x] Chopping. Make sure correct objects get created from plants and get gathered. Make sure dwarves can chop on uneven terrain without getting stuck.
- [x] Attack orders.
- [x] Treasury -- make sure it works. Make sure dwarves gathering coins go to treasury.
- [x] Animal pen -- make sure it works. Make sure dwarves can take animals to pen. Make sure animals stay constrained in pen.
- [x] Cemetery -- make sure corpses get taken to cemetery and dwarves sit at graves to grieve.
- [x] Caves -- make sure they don't have openings into the sea. Make sure fog of war works in caves. Make sure all creatures that should be spawning in caves (spiders, scorpions, bats, and mud men) spawn in them.
- [x] Goal system -- run through the one campaign we have and make sure it works completely.
- [x] Sleeping -- make sure sleepy dwarves go to sleep in beds and that skipping to daytime works.
- [x] Eating -- make sure hungry dwarves eat food properly.
- [x] Trade -- try trading with every race. Make sure its not nonsensical and doesn't cause crashes.
- [x] War -- try going to war with every race.
- [x] Worldgen -- try spawning at the edge of the world or in the middle of the sea.
- [x] Graphics settings -- try the game with and without every major graphics setting. Try in full screen and windowed mode.
- [x] Saving -- try saving the game directly and an autosave.
- [x] Loading -- try loading directly and from autosave.
- [ ] Uptime test -- leave the game running for several hours and make sure it doesn't crash
- [x] Magical research -- make sure that the spell tree can be researched
- [x] Magical spells -- make sure all spells do what they are supposed to
- [x] Magical helper -- make sure magic helper works properly

**Deployment, Marketing and Compatability**
- [ ] Get new builds on Steam and itch.io
- [x] Set up Steam and itch.io to have the correct release date.
- [x] Create a release trailer and attach it to Steam.
- [ ] Create a few more high res screenshots and gifs for marketing
- [x] Make sure bank account details are correct
- [x] Test Steam client on Mac and Linux #192 
- [ ] Test camera controls on Linux #198 
- [x] Spam trailer and release materials on social media
- [x] Get Actual Authority on Steam.

**Comment by plasticware** [comment]
Bad news about ladders...

[ ] craftsdwarf can't build more than one ladder piece at a time - if click-dragging ladder, builds the first piece and then stands there, with task "avoid falling"
[ ] related to above: task was rapidly flickering between nothing and avoid falling - trying to click 'cancel' caused a crash: EmployeeInfo.cs, line 335: Employee.CurrentTask is null.
[ ] ladders are not factored into pathfinding, and seem to be the same speed as scaling plain walls. maybe make twice as fast, half pathfinding cost, 2x animation speed?
[ ] ladders don't spawn correctly on balloon ports, and can't be destroyed. no way to change facing, either, when there is more than one wall on a tile.

**Comment by mklingen** [comment]
Fixed most ladder things on my branch but haven't pushed.

**Comment by mklingen** [comment]
wrangling bugs:
- [ ] animals can trap themselves in pits - dwarves can climb in/out to wrangle them, but animal pathfinding will fail when trying to go to the pen
    - [ ] maybe have the animals trail the dwarves the way barrels do for traders?
- [ ] cannot cancel wrangling attempts
- [ ] dwarves will not reattempt wrangling, even when re-selecting animals
    - [ ] this means if you try to wrangle an animal before you have a pen, your dwarves will never complete the task even after building a pen, since the animal will still be selected and the dwarves will never retry

**Comment by Servius** [comment]
@mklingen Id like to suggest the following to maybe help with release: 

- A button in the escape menu that will quickly allow users to submit bug reports and any pertinent information you would need to assist. (like the crash logs) 
- Consider adding a demo for the game. A short demo to help wait-and-see users commit to buying the game. 
- Add some more gameplay footage to the steam store page. Not a trailer. More like a five minute video with one minute moving from five different stages of the game. Start->Stable. 
- Set up a discord for DwarfCorp.

**Comment by mklingen** [comment]
@Servius all good ideas that I unfortunately don't have time for at the moment, though maybe in the coming days. As for bug reporting, we have an automated system for that now which will hopefully give us a better idea of crashes at least.

**Comment by com1clyf3** [comment]
Sept 23rd has come and gone.
