### ISSUE TITLE
Non-tech checklist for release.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#914]
- [ ] Make some promotional gifs.
- [ ] gif: xray mode
- [ ] gif: necrosnake
- [ ] gif: combat scene
- [ ] Post said gifs to reddit, imgur, twitter.
- [ ] Make 2 minute trailer.
- [ ] Make update to kickstarter backers.
- [ ] Make several new high resolution screenshots.
- [ ] Update promotional text on website.
- [ ] Update Steam promotional materials.
- [ ] Go through Steam checklist for release.
bonus:
- [ ] Get Demo in working order
